// Code generated by mockery v1.0.0. DO NOT EDIT.

// 'Regenerate

package mocks

import mock "github.com/stretchr/testify/mock"

// ThreadStore is an autogenerated mock type for the ThreadStore type
type ThreadStore struct {
	mock.Mock
}
