version: "2.4"

services:
  postgres:
    container_name: postgres_hungknow
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hkuser
      POSTGRES_PASSWORD: mostest
      POSTGRES_DB: hungknow
      TZ:

  hkserver:
    depends_on:
      - postgres
    container_name: hkserver
    image: hungknow/${HUNGKNOW_IMAGE}:${HUNGKNOW_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ${HUNGKNOW_CONFIG_PATH}:/hkserver/config:rw
      - ${HUNGKNOW_DATA_PATH}:/hkserver/data:rw
      - ${HUNGKNOW_LOGS_PATH}:/hkserver/logs:rw
      - ${HUNGKNOW_PLUGINS_PATH}:/hkserver/plugins:rw
      - ${HUNGKNOW_CLIENT_PLUGINS_PATH}:/hkserver/client-plugins:rw
    environment:
      # timezone inside container
      - TZ

      # necessary HungKnow server options/variables (see env.example)
      - HK_SQLSETTINGS_DRIVERNAME
      - HK_SQLSETTINGS_DATASOURCE

      # additional settings
      - HK_SERVICESETTINGS_SITEURL