version: "2.4"

services:
  nginx-data:
    image: hungknow/nginxdata:0.01
    container_name: hknginxdata

  nginx:
    depends_on:
      - hkserver
      - hkwebapp
    container_name: hknginx
    image: nginx:${NGINX_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes_from:
      - nginx-data:ro
    # volumes:
    #   - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d:ro
    #   - ${NGINX_DHPARAMS_FILE}:/dhparams4096.pem
    #   - ${CERT_PATH}:/cert.pem:ro
    #   - ${KEY_PATH}:/key.pem:ro
    #   - shared-webroot:/usr/share/nginx/html
    environment:
      # timezone inside container
      - TZ
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80

  hkwebapp:
    image: hungknow/webapp:0.01
    container_name: hkwebapp
    restart: ${RESTART_POLICY}
    ports:
      - 3000:3000

# Shared volume for Let's Encrypt certificate renewal with a webroot
volumes:
  shared-webroot:
    name: shared-webroot

networks:
  default:
    name: hk-network